version: '3.8'

services:
  postgres:
    build: .
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr",
        "-c",
        "shared_preload_libraries=pg_cron",
        "-c",
        "cron.database_name=edu",
      ]
    container_name: postgres
    environment:
      POSTGRES_USER: arklim
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: edu
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./assets/0001_init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
